Add new stream types for dynamic
sablier-labs/docs pull request #137
Opened 2024-03-25 17:15 UTC by andreivladbrg

Closes https://github.com/sablier-labs/docs/issues/110

@PaulRBerg I have not added explanations for the graphs yet, as I don't know what specific use cases you have in mind for them. Could you share your ideas here? After that, I'll include the explanations accordingly.

The shapes look like the images below:

<details>
<summary> images </summary>

![image](https://github.com/sablier-labs/docs/assets/99738872/c5d5e84d-a4b0-4ad7-ac03-75553fd68298)

![image](https://github.com/sablier-labs/docs/assets/99738872/e560a0a5-4e55-43e2-a34a-293360efc67a)

![image](https://github.com/sablier-labs/docs/assets/99738872/d8d65133-2471-4c79-9964-9b48b10db367)

</details>

2024-04-15 10:56 UTC, PaulRBerg requested changes
The plots look good to me.

Regarding the description for each newly added section - I am sure you can intuit the use cases. I would like to ask you to take a stab at writing the descriptions yourself.

2024-04-17 14:42 UTC, smol-ninja reviewed
The descriptions are very useful and easy to understand. I have added my suggestions below. Also a question for you?

- Should we rename "model" to "shape"?

2024-04-17 14:42 UTC, smol-ninja commented on docs/concepts/protocol/02-stream-types.mdx
> +model is particularly suited for structured yet flexible token distribution plans such as distributing a set salary
How about we say something simple here (it looks a bit complicated to me):

Monthly Unlocks is a special case of Unlock in Steps where assets are unlocked on the same day every month. This is particularly suited for use cases where users want to distribute tokens every month such as distributing salaries.

2024-04-17 14:42 UTC, smol-ninja commented on docs/concepts/protocol/02-stream-types.mdx
> +The Timelock model enables the locking of a certain amount of tokens for a specified period. This model is designed to
```suggestion
The Timelock model enables locking tokens for a specified period. This model is designed to
```

2024-04-17 14:42 UTC, smol-ninja commented on docs/concepts/protocol/02-stream-types.mdx
> +contract term — this is your "salary".
Should we add this as well?

Another use case is a token distribution to investors where a particular amount gets unlocked immediately followed by a linear vesting plan.

2024-04-17 14:42 UTC, smol-ninja commented on docs/concepts/protocol/02-stream-types.mdx
> +linear unlock phase.
How about we add a use case here as well (like all the previous ones)?

This shape is useful for companies who want to distribute tokens to their investors using a cliff followed by linear vesting but also want to unlock some liquidity at the beginning to be able to allow investors to bootstrap AMM pools.

2024-04-17 15:56 UTC, andreivladbrg commented
Thanks for the quick review. I agree with your suggestions and have just pushed the changes you recommended.

> Should we rename "model" to "shape"?

I personally like "model"

2024-04-17 17:50 UTC, smol-ninja commented
It's failing because of this:

<img width="775" alt="Screenshot 2024-04-17 at 18 50 27" src="https://github.com/sablier-labs/docs/assets/6676622/de3ce619-d6dd-4bbd-a08d-c527b631696e">

2024-04-18 08:32 UTC, PaulRBerg commented
Turns out the problem wasn't the NFT descriptor casing. It was Bun and a missing dev dependency (`react-loadable`). See this:

https://discord.com/channels/398180168688074762/867060369087922187/1191397897598672986

The build works now in CI.

2024-04-18 08:32 UTC, PaulRBerg approved these changes
good to be merged

2024-04-18 10:45 UTC, andreivladbrg commented
Thanks for the CI fix, merging now

2024-04-18 10:45 UTC, merged